#!/usr/bin/env python3
# Train a tiny char-level neural language model (Bengio-style MLP-LM) from
# scratch in PURE PYTHON (no numpy/torch), then EMIT a self-contained Loon
# program that runs the forward pass through the loon-hdl compute path
# (embedding -> matmul -> ReLU -> matmul -> argmax) and generates text.
# The model is real (trained by SGD on real text); inference runs in Loon,
# the same op-for-op math the verified loon-hdl hardware computes.
import math, random, copy

CORPUS = (
    "the sun is bright and the sky is blue. "
    "a bird can fly and a fish can swim. "
    "the cat sat on the mat in the sun. "
    "the dog ran and ran in the green grass. "
    "we like to read good books and to learn. "
    "the moon is bright at night and the stars shine. "
)
random.seed(7)

chars = sorted(set(CORPUS))
V = len(chars)
stoi = {c: i for i, c in enumerate(chars)}
itos = {i: c for i, c in enumerate(chars)}
C, E, H = 8, 6, 32          # context, embed dim, hidden
IN = C * E

def randm(r, c, s): return [[random.uniform(-s, s) for _ in range(c)] for _ in range(r)]
emb = randm(V, E, 0.1)
W1, b1 = randm(H, IN, (1.0/IN)**0.5), [0.0] * H     # Xavier-ish
W2, b2 = randm(V, H, (1.0/H)**0.5), [0.0] * V

def relu(z): return z if z > 0 else 0.0
def relu_d(z): return 1.0 if z > 0 else 0.0
def clip(g): return 5.0 if g > 5.0 else (-5.0 if g < -5.0 else g)

data = [([stoi[c] for c in CORPUS[i - C:i]], stoi[CORPUS[i]]) for i in range(C, len(CORPUS))]

def forward(ctx):
    x = [emb[c][k] for c in ctx for k in range(E)]
    z1 = [sum(W1[j][k] * x[k] for k in range(IN)) + b1[j] for j in range(H)]
    h = [relu(z) for z in z1]
    z2 = [sum(W2[j][k] * h[k] for k in range(H)) + b2[j] for j in range(V)]
    m = max(z2); ex = [math.exp(v - m) for v in z2]; s = sum(ex)
    p = [e / s for e in ex]
    return x, z1, h, z2, p

def zl(M): return [[0.0] * len(r) for r in M]
B1, B2, EPS, LR, WD = 0.9, 0.999, 1e-8, 0.01, 1e-4
def adam_mat(P, G, M, Vv, t):
    for i in range(len(P)):
        Pi, Gi, Mi, Vi = P[i], G[i], M[i], Vv[i]
        for k in range(len(Pi)):
            g = Gi[k] + WD * Pi[k]
            Mi[k] = B1 * Mi[k] + (1 - B1) * g
            Vi[k] = B2 * Vi[k] + (1 - B2) * g * g
            Pi[k] -= LR * (Mi[k] / (1 - B1**t)) / (math.sqrt(Vi[k] / (1 - B2**t)) + EPS)
def adam_vec(P, G, M, Vv, t):
    for k in range(len(P)):
        M[k] = B1 * M[k] + (1 - B1) * G[k]
        Vv[k] = B2 * Vv[k] + (1 - B2) * G[k] * G[k]
        P[k] -= LR * (M[k] / (1 - B1**t)) / (math.sqrt(Vv[k] / (1 - B2**t)) + EPS)

mE, vE, mW1, vW1, mW2, vW2 = zl(emb), zl(emb), zl(W1), zl(W1), zl(W2), zl(W2)
mb1, vb1, mb2, vb2 = [0.0]*H, [0.0]*H, [0.0]*V, [0.0]*V
t, best, best_snap = 0, 1e9, None
for epoch in range(120):
    random.shuffle(data); tot = 0.0
    for ctx, y in data:
        t += 1
        x, z1, h, z2, p = forward(ctx)
        tot += -math.log(p[y] + 1e-9)
        dz2 = p[:]; dz2[y] -= 1.0
        gW2 = [[dz2[j] * h[k] for k in range(H)] for j in range(V)]
        dh = [sum(W2[j][k] * dz2[j] for j in range(V)) for k in range(H)]
        dz1 = [dh[k] * relu_d(z1[k]) for k in range(H)]
        gW1 = [[dz1[j] * x[k] for k in range(IN)] for j in range(H)]
        dx = [sum(W1[j][k] * dz1[j] for j in range(H)) for k in range(IN)]
        gE = zl(emb)
        for ci, c in enumerate(ctx):
            for k in range(E): gE[c][k] += dx[ci * E + k]
        adam_mat(W2, gW2, mW2, vW2, t); adam_vec(b2, dz2, mb2, vb2, t)
        adam_mat(W1, gW1, mW1, vW1, t); adam_vec(b1, dz1, mb1, vb1, t)
        adam_mat(emb, gE, mE, vE, t)
    L = tot / len(data)
    if L < best: best, best_snap = L, copy.deepcopy((emb, W1, b1, W2, b2))
    if epoch % 20 == 0 or epoch == 119:
        print(f"  epoch {epoch:3d}  loss/char {L:.3f}  (best {best:.3f})")
emb, W1, b1, W2, b2 = copy.deepcopy(best_snap)
print(f"  restored best (loss/char {best:.3f})")

def gen(seed, n):
    ctx = [stoi[c] for c in seed[-C:]]; out = seed
    for _ in range(n):
        _, _, _, _, p = forward(ctx)
        nx = max(range(V), key=lambda i: p[i])
        out += itos[nx]; ctx = ctx[1:] + [nx]
    return out
print("  python sample:", repr(gen("the sun ", 60)))

# ── emit a self-contained Loon inference program ────────────────────────
def vec(xs):  return "#[" + " ".join(f"{x:.5f}" for x in xs) + "]"
def mat(M):   return "#[" + " ".join(vec(r) for r in M) + "]"
def ivec(xs): return "#[" + " ".join(str(x) for x in xs) + "]"
seed = "the sun "
seed_ids = [stoi[c] for c in seed[-C:]]
itos_words = " ".join(f'"{itos[i]}"' for i in range(V))

loon = f'''; AUTO-GENERATED by train.py — a real trained char-LM, run through loon-hdl.
; Model trained from scratch (SGD) on real text; this runs the forward pass via
; the loon-hdl compute path (embed -> matmul -> ReLU -> matmul -> argmax) in Loon.
; top-level `let` is NOT visible inside fn bodies in Loon — weights are 0-arg fns.
[fn emb [] {mat(emb)}]
[fn w1 [] {mat(W1)}] [fn b1 [] {vec(b1)}]
[fn w2 [] {mat(W2)}] [fn b2 [] {vec(b2)}]
[fn itos [] #[{itos_words}]]

[fn vcat-go [ys i acc] [if [>= i [len ys]] acc [vcat-go ys [+ i 1] [conj acc [nth ys i]]]]]
[fn vcat [xs ys] [vcat-go ys 0 xs]]
[fn dot-go [a b n i acc] [if [>= i n] acc [dot-go a b n [+ i 1] [+ acc [* [nth a i] [nth b i]]]]]]
[fn dot [a b] [dot-go a b [len a] 0 0.0]]
[fn mv-go [w x bs n i acc]
  [if [>= i n] acc [mv-go w x bs n [+ i 1] [conj acc [+ [dot [nth w i] x] [nth bs i]]]]]]
[fn relu-go [v i acc] [if [>= i [len v]] acc [relu-go v [+ i 1] [conj acc [if [> [nth v i] 0.0] [nth v i] 0.0]]]]]
[fn embed-go [ctx j acc] [if [>= j [len ctx]] acc [embed-go ctx [+ j 1] [vcat acc [nth [emb] [nth ctx j]]]]]]
[fn argmax-go [v i best bi] [if [>= i [len v]] bi [if [> [nth v i] best] [argmax-go v [+ i 1] [nth v i] i] [argmax-go v [+ i 1] best bi]]]]

[fn forward [ctx]
  [let x [embed-go ctx 0 #[]]]
  [let z1 [mv-go [w1] x [b1] {H} 0 #[]]]
  [let h [relu-go z1 0 #[]]]
  [let z2 [mv-go [w2] h [b2] {V} 0 #[]]]
  [argmax-go z2 1 [nth z2 0] 0]]

[fn slide [ctx nx i acc] [if [>= i [len ctx]] [conj acc nx] [slide ctx nx [+ i 1] [conj acc [nth ctx i]]]]]
[fn gen-go [ctx n acc]
  [if [<= n 0] acc
    [do
      [let nx [forward ctx]]
      [gen-go [slide ctx nx 1 #[]] [- n 1] [str acc [nth [itos] nx]]]]]]

[fn main []
  [println "=== a real trained char-LM, generating via loon-hdl compute ==="]
  [println [str ">>> " [gen-go {ivec(seed_ids)} 70 "{seed}"]]]]
'''
open("loon-hdl/lm/lm_run.oo", "w").write(loon)
print("  wrote loon-hdl/lm/lm_run.oo  (V=%d H=%d C=%d params=%d)" %
      (V, H, C, V*E + H*IN + H + V*H + V))
