//! A GPU on the other side of a JavaScript function.
//!
//! WebGPU is reachable only through promises, and Loon's VM is synchronous all
//! the way down: a `Place.read` is an ordinary effect operation that returns a
//! value, not a future. Those two facts cannot both be satisfied on one thread.
//!
//! So they are satisfied on two. The VM runs in a Web Worker and every device
//! call goes through the bridge below, which posts a request to the main thread
//! and blocks on `Atomics.wait` until the answer lands in a `SharedArrayBuffer`.
//! The main thread — where the promises live — does the actual WebGPU work and
//! wakes the worker. The blocking is real, and it is the point: it is what lets
//! an asynchronous API sit underneath a synchronous language without either one
//! having to lie about what it is.
//!
//! Nothing here knows about WGSL or wgpu. The shader text arrives already
//! generated by `eir::wgsl`, which is the same text a desktop build hands to
//! wgpu, so the browser and the laptop run the same kernel.

use loon_lang::eir::device::{Device, DeviceError};
use loon_lang::eir::vm::{BufData, Buffer};
use std::cell::RefCell;
use wasm_bindgen::prelude::*;

thread_local! {
    /// The JS function that performs one device operation and returns its
    /// result. Synchronous from here; whatever it does to become synchronous
    /// is its own business.
    static BRIDGE: RefCell<Option<js_sys::Function>> = const { RefCell::new(None) };
}

/// Install the JS side of the bridge.
pub fn set_bridge(f: js_sys::Function) {
    BRIDGE.with(|b| *b.borrow_mut() = Some(f));
}

/// Whether a bridge has been installed.
pub fn has_bridge() -> bool {
    BRIDGE.with(|b| b.borrow().is_some())
}

fn call(op: &str, payload: &JsValue) -> Result<JsValue, DeviceError> {
    BRIDGE.with(|b| {
        let guard = b.borrow();
        let f = guard
            .as_ref()
            .ok_or_else(|| DeviceError("no GPU bridge is installed".to_string()))?;
        f.call2(&JsValue::NULL, &JsValue::from_str(op), payload)
            .map_err(|e| DeviceError(format!("{op}: {}", describe(&e))))
    })
}

/// A thrown JS value, as a sentence.
fn describe(e: &JsValue) -> String {
    e.as_string()
        .or_else(|| {
            js_sys::Reflect::get(e, &JsValue::from_str("message"))
                .ok()
                .and_then(|m| m.as_string())
        })
        .unwrap_or_else(|| format!("{e:?}"))
}

/// A device driven by JavaScript.
pub struct BridgeGpu {
    resident: RefCell<std::collections::HashSet<usize>>,
}

impl BridgeGpu {
    pub fn new() -> BridgeGpu {
        BridgeGpu {
            resident: RefCell::new(std::collections::HashSet::new()),
        }
    }
}

impl Default for BridgeGpu {
    fn default() -> Self {
        Self::new()
    }
}

/// A buffer's bytes, as something JS can read without copying twice.
fn bytes_of(buf: &Buffer) -> js_sys::Uint8Array {
    let bytes = buf.to_bytes();
    let arr = js_sys::Uint8Array::new_with_length(bytes.len() as u32);
    arr.copy_from(&bytes);
    arr
}

fn dtype_name(buf: &Buffer) -> &'static str {
    match &buf.data {
        BufData::F32(_) => "f32",
        BufData::F64(_) => "f32", // narrowed before it gets here
        BufData::I32(_) => "i32",
        BufData::I64(_) => "i32",
    }
}

fn obj(pairs: &[(&str, JsValue)]) -> JsValue {
    let o = js_sys::Object::new();
    for (k, v) in pairs {
        let _ = js_sys::Reflect::set(&o, &JsValue::from_str(k), v);
    }
    o.into()
}

impl Device for BridgeGpu {
    fn name(&self) -> String {
        call("name", &JsValue::NULL)
            .ok()
            .and_then(|v| v.as_string())
            .unwrap_or_else(|| "webgpu".to_string())
    }

    fn ensure_resident(&self, id: usize, buf: &Buffer) -> Result<bool, DeviceError> {
        if self.resident.borrow().contains(&id) {
            return Ok(false);
        }
        call(
            "upload",
            &obj(&[
                ("id", JsValue::from_f64(id as f64)),
                ("dtype", JsValue::from_str(dtype_name(buf))),
                ("bytes", bytes_of(buf).into()),
            ]),
        )?;
        self.resident.borrow_mut().insert(id);
        Ok(true)
    }

    fn is_resident(&self, id: usize) -> bool {
        self.resident.borrow().contains(&id)
    }

    fn dispatch(
        &self,
        shader: &str,
        entry: &str,
        n: u32,
        scalars: &[f32],
        buffers: &[usize],
    ) -> Result<(), DeviceError> {
        let js_scalars = js_sys::Float32Array::new_with_length(scalars.len() as u32);
        js_scalars.copy_from(scalars);
        let js_buffers = js_sys::Array::new();
        for id in buffers {
            js_buffers.push(&JsValue::from_f64(*id as f64));
        }
        call(
            "dispatch",
            &obj(&[
                ("shader", JsValue::from_str(shader)),
                ("entry", JsValue::from_str(entry)),
                ("n", JsValue::from_f64(n as f64)),
                ("scalars", js_scalars.into()),
                ("buffers", js_buffers.into()),
            ]),
        )?;
        Ok(())
    }

    fn download(&self, id: usize, byte_len: usize) -> Result<Vec<u8>, DeviceError> {
        let result = call(
            "download",
            &obj(&[
                ("id", JsValue::from_f64(id as f64)),
                ("byteLength", JsValue::from_f64(byte_len as f64)),
            ]),
        )?;
        let arr = js_sys::Uint8Array::new(&result);
        let mut out = vec![0u8; arr.length() as usize];
        arr.copy_to(&mut out);
        out.truncate(byte_len);
        Ok(out)
    }

    fn evict(&self, id: usize) {
        if self.resident.borrow_mut().remove(&id) {
            let _ = call("evict", &obj(&[("id", JsValue::from_f64(id as f64))]));
        }
    }
}
